---
- name: "Install epel-release"
  yum:
    name: epel-release
    state: present

- name: "Update yum repos and Install Httpd and ufw"
  yum:
    update_cache: True
    name:
        - httpd
        - ufw
    state: latest
  notify:
      - restart_ufw

- name: "Push Http Config for CentosOS/Redhat"
  copy:
    src: files/httpd.conf
    dest: /etc/httpd/conf/httpd.conf

# Copy index.html into the service
- name: copy index.html
  copy:
          mode: 0644
          src: files/index.html
          dest: /var/www/html/
  notify:
     - restart_httpd
