---
- name: "Install apache2 on Debian and Ubuntu"
  apt:
    name: [apache2, ufw]
    state: latest
  notify:
     - restart_ufw

- name: "Push Apache config for Debian or Ubuntu"
  copy:
    src: files/apache2.conf
    dest: /etc/apache2/apache2.conf

# Copy index.html into the service
- name: copy index.html
  copy:
          mode: 0644
          src: files/index.html
          dest: /var/www/html/
  notify:
     - restart_apache
