---
# tasks file for rzfeeser.tuesday
- name: Deploy on CentOS
  import_tasks: centos_tasks.yml
  when: ansible_distribution == "RedHat"

- name: Deploy on Debian / Ubuntu
  import_tasks: debian_tasks.yml
  when: ansible_distribution == "Debian"

# Copy index.html into the service
- name: copy index.html
  copy:
          mode: 0644
          src: files/index.html
          dest: /var/www/html/
  notify:
     - restart_apache
     - restart_httpd
