---
# tasks file for rzfeeser.tuesday
- name: Deploy on CentOS
  import_tasks: centos_tasks.yml
  when: ansible_distribution == "CentOS"

- name: Deploy on Debian / Ubuntu
  import_tasks: debian_tasks.yml
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
